[Step 2] CODA
yagom-academy/ios-my-magical-hand pull request #19
Opened 2021-08-13 10:47 UTC by dacodaco

안녕하세요 도미닉 @AppleCEO 두번째 PR 입니다. 
이번 스텝을 진행하면서 화면 구성, 화면에 사용자의 터치 이벤트를 표현하는 방식을 학습해보았습니다.

---

<img src="https://user-images.githubusercontent.com/74695165/129345876-0cb1a38b-984a-4496-ab64-9a74865a0205.gif" alt="그림그리는화면" width="180">

### 1. 화면 구현
스토리보드 없이 화면을 코드로 구현해보았습니다. 
이 때, 화면 속 각 요소를 DrawingView라는 별도의 UIView 타입으로 만들어 두고, ViewController에서 이를 인스턴스화 하여 사용하게 됩니다.

### 2. 사용자의 터치 이벤트 처리
사용자의 터치 이벤트는 `touchesBegan`, `touchesMoved`, `touchesEnded` 메서드를 재정의하여 활용하였습니다. 

1. touchesBegan
```Swift
override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
    guard let touch = touches.first else {
        return
    }
    swiped = false
    lastPoint = touch.location(in: drawingView.canvasView)
}
```
- 사용자의 터치가 시작될때 swiped (터치 후 움직였는지)를 false로 바꿉니다.
- 터치한 위치를 lastPoint 에 저장합니다.
   - 저장된 lastPoint는 이후 drawLine이라는 메서드에서 활용됩니다. 
- 이 때, 단순히 터치를 시작했다고 시작한 지점에 점이 찍히는 것은 아닙니다. 만약 터치한후 동일한 위치에서 손가락을 떼면, 떼는 순간 점이 찍히도록 설계했습니다.

2. touchesMoved

```Swift
override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
    guard let touch = touches.first else {
        return
    }
    swiped = true
    let currentPoint = touch.location(in: drawingView.canvasView)
    drawLine(from: lastPoint, to: currentPoint)
    lastPoint = currentPoint
}
```
- 움직임을 감지한 메서드이므로 swiped 의 값을 true로 전환합니다.
- 현재의 위치를 currentPoint로 저장합니다.
- 기존의 위치와 현재의 위치를 비교해 line을 그립니다.
- 현재의 위치를 lastPoint에 저장해 다음 움직임을 위해 준비합니다.

3. touchesEnded

```Swift
override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
    if !swiped {
        drawLine(from: lastPoint, to: lastPoint)
    }
}
```
- 손가락을 뗀 위치가 시작 지점인 경우 swiped의 값이 false 이므로 해당 지점에 점이 찍힙니다.
- 그렇지 않은 경우 (touchesMoved에 의해)이미 그림이 그려져 있을 것이므로, 별도의 처리 없이 메서드가 종료됩니다.

---
### 궁금했던 점

- GraphicsImageContext의 초기 설정을 매번 해주지 않으려면 어떻게 해야할까요?

```Swift
func drawLine(from fromPoint: CGPoint, to toPoint: CGPoint) {
    ...
    context.setLineCap(.round)
    context.setBlendMode(.normal)
    context.setLineWidth(brushWidth)
    context.setStrokeColor(color.cgColor)
    drawingView.canvasView.alpha = opacity
    ...
}
```

현재 `drawLine` 메서드를 확인해보면, 
메서드가 호출될 때마다 매번 context의 선굵기, 컬러, 라인 캡 종류, 색혼합설정 등이 할당되고 있음을 알 수 있습니다. 
그렇다는 것은, 손가락이 화면에서 움직일 때마다 굳이 필요하지 않은 코드가 계속 호출된다는 뜻으로 해석할 수도 있겠습니다. 
이와 같은 상황에서 도미닉이라면 어떠한 방식으로 리팩토링을 진행하실지 궁금합니다.

2021-08-15 13:44 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
코드들이 간결하고 이해하기 쉽게 작성하셨습니다!
코멘드들 참고해서 개선해보시면 좋을 것 같습니다~

궁금했던 점
GraphicsImageContext의 초기 설정을 매번 해주지 않으려면 어떻게 해야할까요?
현재 drawLine 메서드를 확인해보면,
메서드가 호출될 때마다 매번 context의 선굵기, 컬러, 라인 캡 종류, 색혼합설정 등이 할당되고 있음을 알 수 있습니다.
그렇다는 것은, 손가락이 화면에서 움직일 때마다 굳이 필요하지 않은 코드가 계속 호출된다는 뜻으로 해석할 수도 있겠습니다.
이와 같은 상황에서 도미닉이라면 어떠한 방식으로 리팩토링을 진행하실지 궁금합니다.
- [공식문서](https://developer.apple.com/documentation/uikit/1623933-uigraphicsendimagecontext)도 찾아보고 여러 예제들 찾아봤습니다. 코다가 작성하신 것처럼 UIGraphicsBeginImageContext 메서드에서 매번 CGContext를 생성하고 UIGraphicsEndImageContext() 메서드를 호출하여 draw 관련 속성을 구성한 내용을 반영하고 있습니다. 이렇게 매번 CGContext 를 생성하기 때문에 바뀌는 속성들은 매번 구성해줘야합니다. 코다가 궁금해하는 초기 설정을 매번 해주지 않는 방법은 없는 것으로 보이네요 ㅜㅜ

2021-08-15 13:44 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand.xcodeproj/project.pbxproj
> +		C7927579262C81C900EF5D3A /* DrawingViewController.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = DrawingViewController.swift; sourceTree = "<group>"; };
뷰컨트롤러의 이름을 바꾼 것 좋습니다!

2021-08-15 13:44 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +    var lastPoint = CGPoint.zero
마지막 점이라고 해석이 되는데요. 어떤 것의 마지막 위치일지 좀 더 정확한 변수명이면 좋을 것 같아요~

2021-08-15 13:44 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +    let opacity: CGFloat = 1.0
color 는 뷰컨트롤러의 칼라면 백그라운드 칼라로 제일 먼저 생각이 되는데 어떤 색상인지 조금 더 자세한 변수명이 있을까요?
opacity도 어떤 뷰의 투명도일지 명확하면 좋을 것 같습니다.

2021-08-15 13:44 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +        self.view.addSubview(drawingView)
self. 가 앞에 붙는 코드와 안 붙는 코드는 어떤 이유로 나눴을까요?
통일이 되면 좋을 것 같네요.

2021-08-15 13:44 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +    }
이 함수는 비어있는데 어떤 역할을 하는지 궁금합니다 ㅎㅎ

2021-08-15 13:44 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +        drawingView.resultButton.addTarget(self, action: #selector(showResult), for: .touchUpInside)
이 코드들에는 제일 앞에 self를 붙이는 것이 좋을까요? 안붙이는 것이 좋을까요? 위에 self.view 와 관련해서 고민해보면 좋을 것 같아요~

2021-08-16 06:40 UTC, dacodaco commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +    }
step 3 에서 버튼을 눌렀을 때 이미지를 비교하고 결과를 보내주는 코드를 넣어줄 예정입니다!
결과 버튼에 대한 타겟 메서드를 미리 만들어주었습니다.

2021-08-16 06:42 UTC, dacodaco commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +        drawingView.resultButton.addTarget(self, action: #selector(showResult), for: .touchUpInside)
사실 self를 붙이는 것과 안붙이는 것 사이에 통일성만 있다면 상관이 없다고 생각했습니다. 

도미닉은 self를 붙이는 방식과 붙이지 않는 방식 사이에 어떤 장단점이 있다고 생각하시나요?

2021-08-16 08:38 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +        drawingView.resultButton.addTarget(self, action: #selector(showResult), for: .touchUpInside)
객체의 프로퍼티일 경우 self. 를 붙이는 식으로 저는 사용하고 있어요.
https://github.com/StyleShare/swift-style-guide
참고해서 통일해보시면 좋을 것 같아요~

2021-08-16 13:23 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +        drawingView.resultButton.addTarget(self, action: #selector(showResult), for: .touchUpInside)
이 부분만 한번 고민해보면 좋을 것 같네요. self 를 붙이는 것과 안 붙이는 것의 차이는 뭘까요?

2021-08-17 01:04 UTC, dacodaco commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +        drawingView.resultButton.addTarget(self, action: #selector(showResult), for: .touchUpInside)
self는 해당 타입의 인스턴스를 의미하기 때문에 타입 내부에서 앞으로 생성될 인스턴스를 의미하는 경우 써주는 것으로 알고 있는데요!

self는 타입 내부의 프로퍼티를 사용하는 경우에 생략될 수 있는 것 같아요. 도미닉은 대부분의 경우에 self를 붙여서 사용하시는 건가요?.?

2021-08-17 03:15 UTC, AppleCEO commented on MyMagicalHand/MyMagicalHand/Controller/DrawingViewController.swift
> +        drawingView.resultButton.addTarget(self, action: #selector(showResult), for: .touchUpInside)
네 저는 타입 내부의 프로퍼티를 사용할 때 붙여서 쓰고 있어요. 메소드 내부 변수와 구분해주기 위해서요. 
이렇게 코드 하나도 의미가 있어야합니다.
고민은 해보신 것 같으니 앞으로 규칙을 정해서 작성해주세요~

2021-08-17 03:17 UTC, merged